// Blume configuration for the nexus-architect report site.
//
// Everything Blume reads — docs/, public/, specs/ — is produced by sync_reports.py from a
// project's reports/ tree, so this file only wires up the pieces that cannot be inferred
// from the files: the custom frontmatter key the sync writes, and the OpenAPI / AsyncAPI
// specs it copied. Run it through tools/docs-site.sh rather than `blume` directly.
import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "blume";
import { z } from "zod";

interface SpecManifest {
  project?: string;
  openapi: { spec: string; label?: string; route?: string }[];
  asyncapi: { spec: string; label?: string; route?: string }[];
}

const manifest: SpecManifest = existsSync("specs/manifest.json")
  ? JSON.parse(readFileSync("specs/manifest.json", "utf8"))
  : { openapi: [], asyncapi: [] };

const title = manifest.project ? `${manifest.project} — reports` : "nexus-architect reports";

export default defineConfig({
  title,
  description: "Analysis and design documents generated by the nexus-architect pipeline.",

  content: {
    root: "docs",
    include: ["**/*.{md,mdx}"],
  },

  frontmatter: {
    // The sync moves every report's own frontmatter (skill, phase, generated_at, ADR ids, …)
    // under this single key: Blume rejects unknown frontmatter, and its built-in keys
    // (`id`, `status`) collide with the ADR shape.
    extend: {
      nexus: z.record(z.string(), z.any()).optional(),
    },
  },

  // Reports are Japanese or English per project; rendering is the same either way.
  theme: { mode: "system" },
  search: { provider: "orama" },
  markdown: { imageZoom: true, code: { wrap: true } },
  toc: { minHeadingLevel: 2, maxHeadingLevel: 3 },
  ai: { llmsTxt: true },
  seo: { og: { enabled: false }, sitemap: false, robots: false },

  openapi: manifest.openapi.length
    ? { enabled: true, route: "/api", playground: false, sources: manifest.openapi }
    : undefined,
  asyncapi: manifest.asyncapi.length
    ? { enabled: true, route: "/events", playground: false, sources: manifest.asyncapi }
    : undefined,

  deployment: { output: "static" },
});
